<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <ItemGroup>
    <ProjectReference Include="..\src\Api\Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.2" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.2" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>c22a60e7-dd59-405e-bc80-ca2f60488063</UserSecretsId>
  </PropertyGroup>

</Project>
